#incident_info:
#  incident_size: 30 # 사고 규모 (총 환자 수)
#  latitude: 37.465833 # 위도
#  longitude: 126.443333 # 경도
#  incident_type: null # 사고 타입 설정 가능하게 추후 확장

entity_info:
  patient:
    incident_size: 30 # 사고 규모 (총 환자 수)
    latitude: 37.465833 # 위도
    longitude: 126.443333 # 경도
    incident_type: null # 사고 타입 설정 가능하게 추후 확장
    info_path: "./scenarios/incheon_airport/patient_info.csv"
  hospital:
    load_data: True
    info_path: "./scenarios/incheon_airport/hospital_info.csv"
    dist_Hos2Hos_euc_info: "./scenarios/incheon_airport/distance_Hos2Hos_euc.csv" # if null, generate
    dist_Hos2Hos_road_info: "./scenarios/incheon_airport/distance_Hos2Hos_road.csv" # if null, generate
    dist_Hos2Site_euc_info: "./scenarios/incheon_airport/distance_Hos2Site_euc.csv" # if null, generate
    dist_Hos2Site_road_info: "./scenarios/incheon_airport/distance_Hos2Site_road.csv" # if null, generate
    max_send_coeff: [1,1] # 각 병원에 보낼 최대 환자수 산술식의 (a,b): max_send = a*max_capa + b*max_queue
  ambulance:
    load_data: True
    #    info_path: "XX" # 부가적인 정보 필요 시 추가
    dispatch_distance_info: "./scenarios/incheon_airport/amb_info.csv" # if null, generate
    velocity: 40 # unit: km/h
    handover_time: 0 # unit: minutes
  uav:
    load_data: True
    #    info_path: "./scenarios/incheon_airport/uav_info.csv" # 부가적인 정보 필요 시 추가
    dispatch_distance_info: "./scenarios/incheon_airport/uav_info.csv" # if null, generate
    velocity: 80 # unit: km/h
    handover_time: 0 # unit: minutes

event_info_path: "event_info.json"

rule_info:
  isFullFactorial: True
  priority_rule: ["START", "ReSTART"] # ["START", "ReSTART"]
  hos_select_rule: ["RedOnly", "YellowHalf"] # ["RedOnly", "YellowHalf"]
  red_mode_rule: ["OnlyUAV", "Both_UAVFirst", "Both_AMBFirst", "OnlyAMB"] # ["OnlyUAV", "Both_UAVFirst", "Both_AMBFirst", "OnlyAMB"]
  yellow_mode_rule: ["OnlyUAV", "Both_UAVFirst", "Both_AMBFirst", "OnlyAMB"] # ["OnlyUAV", "Both_UAVFirst", "Both_AMBFirst", "OnlyAMB"]

run_setting:
  totalSamples: 10 # number of samples
  random_seed: 0 # null, if do not want to fix
  rule_test: True
  eval_mode: True
  output_path: "./results"
  exp_indicator: "시나리오이름"
  save_info: True # NotImplemented
