#incident_info:
#  incident_size: 30 # 사고 규모 (총 환자 수)
#  latitude: 37.493334 # 위도
#  longitude: 126.687087 # 경도
#  incident_type: null # 사고 타입 설정 가능하게 추후 확장

entity_info:
  patient:
    incident_size: 30 # 사고 규모 (총 환자 수)
    latitude: 37.493334 # 위도
    longitude: 126.687087 # 경도
    incident_type: null # 사고 타입 설정 가능하게 추후 확장
    info_path: "./scenarios/exp_20250903_181948/(37.493334,126.687087)/patient_info.csv"
  hospital:
    load_data: True
    info_path: "./scenarios/exp_20250903_181948/(37.493334,126.687087)/hospital_info_road.csv"
    dist_Hos2Hos_euc_info: "./scenarios/exp_20250903_181948/(37.493334,126.687087)/distance_Hos2Hos_euc.csv"
    dist_Hos2Hos_road_info: "./scenarios/exp_20250903_181948/(37.493334,126.687087)/distance_Hos2Hos_road.csv"
    dist_Hos2Site_euc_info: "./scenarios/exp_20250903_181948/(37.493334,126.687087)/distance_Hos2Site_euc.csv"
    dist_Hos2Site_road_info: "./scenarios/exp_20250903_181948/(37.493334,126.687087)/distance_Hos2Site_road.csv"
    max_send_coeff: [1.0, 1.0]
  ambulance:
    load_data: True
    dispatch_distance_info: "./scenarios/exp_20250903_181948/(37.493334,126.687087)/amb_info_road.csv"
    velocity: 40 # unit: km/h
    handover_time: 0 # unit: minutes
  uav:
    load_data: True
    dispatch_distance_info: "./scenarios/exp_20250903_181948/(37.493334,126.687087)/uav_info.csv"
    velocity: 80 # unit: km/h
    handover_time: 0 # unit: minutes

event_info_path: "event_info.json"

rule_info:
  isFullFactorial: True
  priority_rule: ["START", "ReSTART"]
  hos_select_rule: ["RedOnly", "YellowHalf"]
  red_mode_rule: ["OnlyUAV", "Both_UAVFirst", "Both_AMBFirst", "OnlyAMB"]
  yellow_mode_rule: ["OnlyUAV", "Both_UAVFirst", "Both_AMBFirst", "OnlyAMB"]

run_setting:
  totalSamples: 10 # number of samples
  random_seed: 0 # null, if do not want to fix
  rule_test: True
  eval_mode: True
  output_path: "./results/exp_20250903_181948"
  exp_indicator: "(37.493334,126.687087)"
  save_info: True # NotImplemented